# Generated by Django 4.2.2 on 2023-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_calories',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
